# This rule is not used by the project splunk-token-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to splunktoken.managed.openshift.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: splunk-token-operator
    app.kubernetes.io/managed-by: kustomize
  name: splunktoken-viewer-role
rules:
- apiGroups:
  - splunktoken.managed.openshift.io
  resources:
  - splunktokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - splunktoken.managed.openshift.io
  resources:
  - splunktokens/status
  verbs:
  - get
