apiVersion: splunktoken.managed.openshift.io/v1alpha1
kind: SplunkToken
metadata:
  labels:
    app.kubernetes.io/name: splunk-token-operator
    app.kubernetes.io/managed-by: kustomize
  name: splunktoken-example
spec:
  name: "example-token"
  defaultIndex: "example-splunk-index"
  allowedIndexes:
    - "another-example-index"
    - "third-example-index"
